package active

// Code generated by genconstants; DO NOT EDIT.

type TagsType struct {
	Awfa         string
	SomeOtherTag string
}

var Tags = TagsType{
	Awfa:         "123",
	SomeOtherTag: "456",
}

var TagsByID = map[string]string{
	"123": "Awfa",
	"456": "SomeOtherTag",
}

type ListsType struct {
	Students string
}

var Lists = ListsType{
	Students: "10",
}

var ListsByID = map[string]string{
	"10": "Students",
}

type FieldsType struct {
	RtoID string
}

var Fields = FieldsType{
	RtoID: "20",
}

var FieldsByID = map[string]string{
	"20": "RtoID",
}
